-- GENERATED by scripts/generate-seed.ts from src/lib/catalog/seed-data.ts. Do not edit.
-- SAMPLE data: replace products, prices, shipping rates and placeholders in the admin panel.
begin;

insert into public.categories (id, name_sq, name_en, intro_sq, intro_en, sort) values
  ('bridal', 'Nusëri', 'Bridal', 'Fustane nusërie të punuara me dorë në Prizren, në masat standarde ose të qepura sipas masave të tua.', 'Handmade wedding dresses from Prizren, in standard sizes or cut to your measurements.', 1),
  ('evening', 'Mbrëmje', 'Evening', 'Fustane mbrëmjeje për ceremoni, darka dhe netë që mbahen mend.', 'Evening dresses for ceremonies, dinners and nights worth remembering.', 2),
  ('short', 'Të shkurtra', 'Short', 'Fustane të shkurtra për kurorëzimin civil, festat dhe mbrëmjet më të lira.', 'Short dresses for civil ceremonies, celebrations and lighter evenings.', 3)
on conflict (id) do nothing;

insert into public.measurement_definitions (id, kind, view, label_sq, label_en, hint_sq, hint_en, min_cm, max_cm, always_required, sort) values
  ('height', 'straight', 'front', 'Gjatësia e trupit', 'Height', 'Zbathur, drejt pranë murit, nga dyshemeja deri në majë të kokës.', 'Barefoot, standing straight against a wall, from the floor to the top of your head.', 140, 200, true, 1),
  ('bust', 'around', 'front', 'Perimetri i gjoksit', 'Bust circumference', 'Rreth pjesës më të plotë të gjoksit, me shiritin drejt përmes shpinës.', 'Around the fullest part of your bust, with the tape level across your back.', 70, 150, true, 2),
  ('underbust', 'around', 'front', 'Perimetri nën gjoks', 'Under bust circumference', 'Menjëherë nën gjoks, aty ku qëndron shiriti i sutjenës.', 'Directly under your bust, where a bra band sits.', 60, 130, true, 3),
  ('waist', 'around', 'front', 'Perimetri i belit', 'Waist circumference', 'Rreth pjesës më të ngushtë të belit, zakonisht pak mbi kërthizë.', 'Around the narrowest part of your waist, usually just above the navel.', 50, 140, true, 4),
  ('hips', 'around', 'side', 'Perimetri i vitheve në pjesën më të gjerë', 'Hip circumference at the fullest part', 'Me këmbët bashkë, rreth pjesës më të plotë të vitheve.', 'Feet together, around the fullest part of your seat.', 75, 160, true, 5),
  ('shoulder_width', 'straight', 'back', 'Gjerësia e shpatullave', 'Shoulder width', 'Përmes shpinës, nga maja e njërës shpatull te maja e tjetrës.', 'Across your back, from one shoulder point to the other.', 30, 55, true, 6),
  ('hollow_to_floor', 'straight', 'front', 'Nga gropëza e qafës deri në dysheme', 'Hollow to floor', 'Zbathur, nga gropëza në fund të qafës drejt poshtë deri në dysheme.', 'Barefoot, from the hollow at the base of your neck straight down to the floor.', 120, 175, true, 7),
  ('heel_height', 'heel', 'shoe', 'Lartësia e takës që do të mbash', 'Heel height you will wear', 'Nga dyshemeja deri aty ku mbështetet thembra. Shkruaj 0 për këpucë pa takë.', 'From the floor to where your heel rests. Enter 0 for flat shoes.', 0, 15, true, 8),
  ('neck', 'around', 'front', 'Perimetri i qafës', 'Neck circumference', 'Rreth bazës së qafës, me një gisht nën shirit.', 'Around the base of your neck, with one finger under the tape.', 28, 50, false, 9),
  ('bicep', 'around', 'front', 'Perimetri i krahut', 'Bicep circumference', 'Rreth pjesës më të plotë të krahut të sipërm, me krahun të lirshëm.', 'Around the fullest part of your upper arm, arm relaxed.', 20, 50, false, 10),
  ('sleeve_length', 'straight', 'side', 'Gjatësia e mëngës', 'Sleeve length', 'Nga maja e shpatullës deri te kocka e kyçit, me krahun pak të përkulur.', 'From the shoulder point to the wrist bone, arm slightly bent.', 40, 70, false, 11),
  ('wrist', 'around', 'front', 'Perimetri i kyçit të dorës', 'Wrist circumference', 'Rreth kyçit të dorës, pak mbi kockën e kyçit.', 'Around your wrist, just above the wrist bone.', 12, 25, false, 12),
  ('front_waist_length', 'straight', 'front', 'Gjatësia e përparme deri në bel', 'Front waist length', 'Nga shpatulla, aty ku takon qafën, mbi majën e gjoksit deri në bel.', 'From where your shoulder meets your neck, over the bust point, down to the waist.', 30, 55, false, 13),
  ('back_length', 'straight', 'back', 'Gjatësia e shpinës', 'Back length', 'Nga kocka në fund të qafës drejt poshtë deri në bel.', 'From the bone at the base of your neck straight down to your waist.', 32, 50, false, 14),
  ('bust_point_height', 'straight', 'front', 'Lartësia e majës së gjoksit', 'Bust point height', 'Nga shpatulla, aty ku takon qafën, deri te maja e gjoksit.', 'From where your shoulder meets your neck down to the bust point.', 18, 35, false, 15),
  ('hollow_to_hem', 'straight', 'front', 'Nga gropëza e qafës deri te fundi', 'Hollow to hem', 'Nga gropëza në fund të qafës deri aty ku dëshiron të përfundojë fustani.', 'From the hollow at the base of your neck to where you want the hem to fall.', 60, 120, false, 16),
  ('waist_to_knee', 'straight', 'side', 'Nga beli deri te gjuri', 'Waist to knee', 'Nga beli natyral deri në mes të gjurit.', 'From your natural waist to the middle of your knee.', 45, 70, false, 17)
on conflict (id) do nothing;

-- Drita
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('drita', 'bridal', 'Drita', 'Drita', 'Fustan nusërie në krep mëndafshi, me jakë të lartë dhe mëngë të gjata. Një vijë e pastër që lë dritën të bjerë mbi ty.', 'A silk crepe wedding gown with a high neck and long sleeves. One clean line that lets the light fall on you.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 145000, 'made_to_order', 8, 'floor', 'long', 'column', true, true, now() - interval '3 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'drita'), v.* from (values
  ('Fildish', 'Ivory', '#F4EDE1', 'ivory', 0),
  ('E bardhë', 'White', '#FBFAF7', 'white', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'drita'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'drita'), 'XS', 0),
  ((select id from public.products where slug = 'drita'), 'S', 1),
  ((select id from public.products where slug = 'drita'), 'M', 1),
  ((select id from public.products where slug = 'drita'), 'L', 0),
  ((select id from public.products where slug = 'drita'), 'XL', 0),
  ((select id from public.products where slug = 'drita'), 'XXL', 0)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'drita'), 'neck'),
  ((select id from public.products where slug = 'drita'), 'bicep'),
  ((select id from public.products where slug = 'drita'), 'sleeve_length'),
  ((select id from public.products where slug = 'drita'), 'wrist')
on conflict do nothing;

-- Bora
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('bora', 'bridal', 'Bora', 'Bora', 'Fustan me fund të gjerë prej tyli dhe korse të modeluar me dorë. Shtresa të lehta që lëvizin me çdo hap.', 'A full tulle skirt beneath a hand-shaped corset. Light layers that move with every step.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 160000, 'made_to_order', 10, 'floor', 'sleeveless', 'ball-gown', true, true, now() - interval '12 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'bora'), v.* from (values
  ('Fildish', 'Ivory', '#F4EDE1', 'ivory', 0),
  ('Shampanjë', 'Champagne', '#EADBC4', 'champagne', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'bora'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'bora'), 'XS', 0),
  ((select id from public.products where slug = 'bora'), 'S', 0),
  ((select id from public.products where slug = 'bora'), 'M', 0),
  ((select id from public.products where slug = 'bora'), 'L', 0),
  ((select id from public.products where slug = 'bora'), 'XL', 0),
  ((select id from public.products where slug = 'bora'), 'XXL', 0)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'bora'), 'front_waist_length'),
  ((select id from public.products where slug = 'bora'), 'back_length'),
  ((select id from public.products where slug = 'bora'), 'bust_point_height')
on conflict do nothing;

-- Lirika
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('lirika', 'bridal', 'Lirika', 'Lirika', 'Dantellë mbi krep, me shpatulla të zbuluara dhe fund në formë A. Butë, romantike dhe e lehtë për t''u mbajtur gjithë natën.', 'Lace over crepe, off the shoulder, with an A-line skirt. Soft, romantic and easy to wear all night.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 125000, 'in_stock', null, 'floor', 'short', 'a-line', true, false, now() - interval '30 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'lirika'), v.* from (values
  ('Fildish', 'Ivory', '#F4EDE1', 'ivory', 0)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'lirika'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'lirika'), 'XS', 1),
  ((select id from public.products where slug = 'lirika'), 'S', 2),
  ((select id from public.products where slug = 'lirika'), 'M', 2),
  ((select id from public.products where slug = 'lirika'), 'L', 1),
  ((select id from public.products where slug = 'lirika'), 'XL', 0),
  ((select id from public.products where slug = 'lirika'), 'XXL', 0)
on conflict do nothing;

-- Yllka
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('yllka', 'bridal', 'Yllka', 'Yllka', 'Siluetë sirenë në saten, me qëndisje të imët që ngjitet nga fundi. Për nusen që do të ndihet e mbledhur dhe e sigurt.', 'A satin mermaid silhouette with fine embroidery rising from the hem. For the bride who wants to feel held and certain.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 138000, 'made_to_order', 9, 'floor', 'sleeveless', 'mermaid', true, false, now() - interval '45 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'yllka'), v.* from (values
  ('Fildish', 'Ivory', '#F4EDE1', 'ivory', 0),
  ('Rozë e zbehtë', 'Blush', '#EBD3CB', 'blush', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'yllka'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'yllka'), 'XS', 0),
  ((select id from public.products where slug = 'yllka'), 'S', 0),
  ((select id from public.products where slug = 'yllka'), 'M', 0),
  ((select id from public.products where slug = 'yllka'), 'L', 0),
  ((select id from public.products where slug = 'yllka'), 'XL', 0),
  ((select id from public.products where slug = 'yllka'), 'XXL', 0)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'yllka'), 'front_waist_length'),
  ((select id from public.products where slug = 'yllka'), 'back_length'),
  ((select id from public.products where slug = 'yllka'), 'bust_point_height')
on conflict do nothing;

-- Nata
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('nata', 'evening', 'Nata', 'Nata', 'Kadife e zezë, mëngë të gjata dhe një prerje e thellë në shpinë. E qetë përpara, e guximshme kur largohesh.', 'Black velvet, long sleeves and a deep cut at the back. Quiet from the front, daring as you walk away.', 'Pastrim kimik. Hekuros me avull nga ana e brendshme, në temperaturë të ulët.', 'Dry clean only. Steam from the inside at a low temperature.', 69000, 'in_stock', null, 'floor', 'long', 'column', true, true, now() - interval '1 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'nata'), v.* from (values
  ('E zezë', 'Black', '#1E1B1A', 'black', 0),
  ('Bordo', 'Burgundy', '#5C1F2B', 'red', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'nata'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'nata'), 'XS', 1),
  ((select id from public.products where slug = 'nata'), 'S', 2),
  ((select id from public.products where slug = 'nata'), 'M', 3),
  ((select id from public.products where slug = 'nata'), 'L', 2),
  ((select id from public.products where slug = 'nata'), 'XL', 1),
  ((select id from public.products where slug = 'nata'), 'XXL', 1)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'nata'), 'bicep'),
  ((select id from public.products where slug = 'nata'), 'sleeve_length'),
  ((select id from public.products where slug = 'nata'), 'wrist')
on conflict do nothing;

-- Vera
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('vera', 'evening', 'Vera', 'Vera', 'Fustan i rrëshqitshëm në saten shampanjë, me rripa të hollë. Bie lirshëm dhe kap dritën në çdo lëvizje.', 'A champagne satin slip dress on fine straps. It falls loosely and catches the light as you move.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 52000, 'in_stock', null, 'floor', 'sleeveless', 'slip', true, false, now() - interval '6 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'vera'), v.* from (values
  ('Shampanjë', 'Champagne', '#D9C3A0', 'champagne', 0),
  ('Argjend', 'Silver', '#C9C7C4', 'silver', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'vera'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'vera'), 'XS', 2),
  ((select id from public.products where slug = 'vera'), 'S', 3),
  ((select id from public.products where slug = 'vera'), 'M', 3),
  ((select id from public.products where slug = 'vera'), 'L', 2),
  ((select id from public.products where slug = 'vera'), 'XL', 1),
  ((select id from public.products where slug = 'vera'), 'XXL', 0)
on conflict do nothing;

-- Hëna
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('hena', 'evening', 'Hëna', 'Hëna', 'Fustan me xixa të qepura një nga një, me jakë të lartë dhe shpinë të hapur. Për netët kur do të shkëlqesh pa u përpjekur.', 'Sequins sewn on one by one, a high neck and an open back. For nights when you want to shine without trying.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 89000, 'made_to_order', 6, 'floor', 'sleeveless', 'column', true, false, now() - interval '9 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'hena'), v.* from (values
  ('Argjend', 'Silver', '#BDBAB5', 'silver', 0),
  ('Ar i zbehtë', 'Pale gold', '#D8C08E', 'champagne', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'hena'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'hena'), 'XS', 0),
  ((select id from public.products where slug = 'hena'), 'S', 0),
  ((select id from public.products where slug = 'hena'), 'M', 1),
  ((select id from public.products where slug = 'hena'), 'L', 0),
  ((select id from public.products where slug = 'hena'), 'XL', 0),
  ((select id from public.products where slug = 'hena'), 'XXL', 0)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'hena'), 'neck')
on conflict do nothing;

-- Mira
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('mira', 'evening', 'Mira', 'Mira', 'Krep smeraldi me një shpatull të zbuluar dhe korse të brendshëm. Një ngjyrë e thellë për një mbrëmje të gjatë.', 'Emerald crepe on one shoulder, with an inner corset. A deep colour for a long evening.', 'Pastrim kimik. Hekuros me avull nga ana e brendshme, në temperaturë të ulët.', 'Dry clean only. Steam from the inside at a low temperature.', 76000, 'made_to_order', 5, 'floor', 'sleeveless', 'sheath', true, false, now() - interval '18 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'mira'), v.* from (values
  ('Smerald', 'Emerald', '#1F4A3D', 'green', 0),
  ('E zezë', 'Black', '#1E1B1A', 'black', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'mira'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'mira'), 'XS', 0),
  ((select id from public.products where slug = 'mira'), 'S', 1),
  ((select id from public.products where slug = 'mira'), 'M', 1),
  ((select id from public.products where slug = 'mira'), 'L', 1),
  ((select id from public.products where slug = 'mira'), 'XL', 0),
  ((select id from public.products where slug = 'mira'), 'XXL', 0)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'mira'), 'front_waist_length'),
  ((select id from public.products where slug = 'mira'), 'back_length'),
  ((select id from public.products where slug = 'mira'), 'bust_point_height')
on conflict do nothing;

-- Zana
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('zana', 'evening', 'Zana', 'Zana', 'Shifon në rozë të pluhurosur, me mëngë të gjata të tejdukshme që rrjedhin si pelerinë. E lehtë si ajri.', 'Dusty rose chiffon with long sheer sleeves that flow like a cape. As light as air.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 64000, 'in_stock', null, 'floor', 'long', 'a-line', true, false, now() - interval '24 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'zana'), v.* from (values
  ('Rozë e pluhurosur', 'Dusty rose', '#C9A3A0', 'blush', 0),
  ('Blu e mjegullt', 'Mist blue', '#A9B4BF', 'blue', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'zana'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'zana'), 'XS', 1),
  ((select id from public.products where slug = 'zana'), 'S', 1),
  ((select id from public.products where slug = 'zana'), 'M', 2),
  ((select id from public.products where slug = 'zana'), 'L', 2),
  ((select id from public.products where slug = 'zana'), 'XL', 1),
  ((select id from public.products where slug = 'zana'), 'XXL', 1)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'zana'), 'bicep'),
  ((select id from public.products where slug = 'zana'), 'sleeve_length'),
  ((select id from public.products where slug = 'zana'), 'wrist')
on conflict do nothing;

-- Lule
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('lule', 'short', 'Lule', 'Lule', 'Dantellë në ngjyrë rozë të zbehtë, deri te gjuri, me mëngë të shkurtra. E përshtatshme për kurorëzimin civil.', 'Blush lace to the knee with short sleeves. Made for a civil ceremony.', 'Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.', 'Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.', 42000, 'in_stock', null, 'knee', 'short', 'a-line', true, true, now() - interval '2 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'lule'), v.* from (values
  ('Rozë e zbehtë', 'Blush', '#EBD3CB', 'blush', 0),
  ('Fildish', 'Ivory', '#F4EDE1', 'ivory', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'lule'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'lule'), 'XS', 2),
  ((select id from public.products where slug = 'lule'), 'S', 3),
  ((select id from public.products where slug = 'lule'), 'M', 3),
  ((select id from public.products where slug = 'lule'), 'L', 2),
  ((select id from public.products where slug = 'lule'), 'XL', 1),
  ((select id from public.products where slug = 'lule'), 'XXL', 1)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'lule'), 'hollow_to_hem')
on conflict do nothing;

-- Era
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('era', 'short', 'Era', 'Era', 'Fustan i shkurtër prej krepi në ngjyrë fildishi, me një fjongo të madhe në shpinë. I thjeshtë, me një detaj që mbahet mend.', 'A short ivory crepe dress with a large bow at the back. Simple, with one detail that stays with you.', 'Pastrim kimik. Hekuros me avull nga ana e brendshme, në temperaturë të ulët.', 'Dry clean only. Steam from the inside at a low temperature.', 35000, 'in_stock', null, 'mini', 'sleeveless', 'shift', true, false, now() - interval '14 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'era'), v.* from (values
  ('Fildish', 'Ivory', '#F4EDE1', 'ivory', 0),
  ('E zezë', 'Black', '#1E1B1A', 'black', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'era'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'era'), 'XS', 2),
  ((select id from public.products where slug = 'era'), 'S', 2),
  ((select id from public.products where slug = 'era'), 'M', 3),
  ((select id from public.products where slug = 'era'), 'L', 2),
  ((select id from public.products where slug = 'era'), 'XL', 1),
  ((select id from public.products where slug = 'era'), 'XXL', 0)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'era'), 'waist_to_knee')
on conflict do nothing;

-- Dea
insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values ('dea', 'short', 'Dea', 'Dea', 'Saten i zi deri te gjuri, me korse të brendshëm dhe prerje të pastër. Për darkën pas ceremonisë.', 'Black satin to the knee, with an inner corset and a clean cut. For the dinner after the ceremony.', 'Pastrim kimik. Hekuros me avull nga ana e brendshme, në temperaturë të ulët.', 'Dry clean only. Steam from the inside at a low temperature.', 48000, 'made_to_order', 4, 'knee', 'sleeveless', 'sheath', true, false, now() - interval '21 days')
on conflict (slug) do nothing;
insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)
select (select id from public.products where slug = 'dea'), v.* from (values
  ('E zezë', 'Black', '#1E1B1A', 'black', 0),
  ('Bordo', 'Burgundy', '#5C1F2B', 'red', 1)
) as v(name_sq, name_en, hex, family, sort)
where not exists (select 1 from public.product_colors where product_id = (select id from public.products where slug = 'dea'));
insert into public.product_sizes (product_id, size, stock) values
  ((select id from public.products where slug = 'dea'), 'XS', 0),
  ((select id from public.products where slug = 'dea'), 'S', 1),
  ((select id from public.products where slug = 'dea'), 'M', 1),
  ((select id from public.products where slug = 'dea'), 'L', 0),
  ((select id from public.products where slug = 'dea'), 'XL', 0),
  ((select id from public.products where slug = 'dea'), 'XXL', 0)
on conflict do nothing;
insert into public.product_measurements (product_id, measurement_id) values
  ((select id from public.products where slug = 'dea'), 'front_waist_length'),
  ((select id from public.products where slug = 'dea'), 'back_length'),
  ((select id from public.products where slug = 'dea'), 'bust_point_height'),
  ((select id from public.products where slug = 'dea'), 'hollow_to_hem')
on conflict do nothing;

insert into public.collections (slug, name_sq, name_en, description_sq, description_en, published, sort)
values ('ceremonia', 'Ceremonia', 'Ceremony', 'Fustanet për ditën kur thua po.', 'Dresses for the day you say yes.', true, 1)
on conflict (slug) do nothing;
insert into public.collection_products (collection_id, product_id, sort)
select c.id, p.id, v.sort from (values ('drita', 0), ('bora', 1), ('lirika', 2), ('yllka', 3), ('lule', 4)) as v(slug, sort)
join public.products p on p.slug = v.slug
join public.collections c on c.slug = 'ceremonia'
on conflict do nothing;

insert into public.collections (slug, name_sq, name_en, description_sq, description_en, published, sort)
values ('dritat-e-mbremjes', 'Dritat e mbrëmjes', 'Evening Light', 'Fustane që kapin dritën kur bie nata.', 'Dresses that catch the light as night falls.', true, 2)
on conflict (slug) do nothing;
insert into public.collection_products (collection_id, product_id, sort)
select c.id, p.id, v.sort from (values ('nata', 0), ('vera', 1), ('hena', 2), ('mira', 3), ('zana', 4), ('dea', 5)) as v(slug, sort)
join public.products p on p.slug = v.slug
join public.collections c on c.slug = 'dritat-e-mbremjes'
on conflict do nothing;

-- Shipping (sample rates)
do $$
declare z uuid;
begin
  if exists (select 1 from public.shipping_zones) then return; end if;
  insert into public.shipping_zones (name_sq, name_en, countries, is_fallback, sort) values ('Kosovë', 'Kosovo', array['XK'], false, 0) returning id into z;
  insert into public.shipping_rates (zone_id, name_sq, name_en, price_cents, free_over_cents, min_days, max_days, sort) values (z, 'Standarde', 'Standard', 500, null, 1, 3, 0);
  insert into public.shipping_zones (name_sq, name_en, countries, is_fallback, sort) values ('Shqipëri dhe Maqedoni e Veriut', 'Albania and North Macedonia', array['AL', 'MK'], false, 1) returning id into z;
  insert into public.shipping_rates (zone_id, name_sq, name_en, price_cents, free_over_cents, min_days, max_days, sort) values (z, 'Standarde', 'Standard', 1500, null, 3, 6, 0);
  insert into public.shipping_zones (name_sq, name_en, countries, is_fallback, sort) values ('Evropë', 'Europe', array['AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK'], false, 2) returning id into z;
  insert into public.shipping_rates (zone_id, name_sq, name_en, price_cents, free_over_cents, min_days, max_days, sort) values (z, 'Standarde', 'Standard', 3500, null, 5, 10, 0);
  insert into public.shipping_rates (zone_id, name_sq, name_en, price_cents, free_over_cents, min_days, max_days, sort) values (z, 'Ekspres', 'Express', 6000, null, 2, 4, 1);
  insert into public.shipping_zones (name_sq, name_en, countries, is_fallback, sort) values ('Pjesa tjetër e botës', 'Rest of the world', '{}'::text[], true, 3) returning id into z;
  insert into public.shipping_rates (zone_id, name_sq, name_en, price_cents, free_over_cents, min_days, max_days, sort) values (z, 'Ndërkombëtare', 'International', 7000, null, 7, 15, 0);
end $$;

insert into public.discount_codes (code, kind, value, usage_limit, expires_at) values
  ('MIRESEVINI10', 'percent', 10, 100, '2027-12-31T23:59:59Z')
on conflict (code) do nothing;

insert into public.payment_methods (id, sort, details) values
  ('paysera', 1, '{}'::jsonb),
  ('bank_transfer', 2, '{"bankName":"[BANK NAME]","beneficiary":"[BENEFICIARY]","iban":"[IBAN]","swift":"[SWIFT]"}'::jsonb),
  ('cash_agency', 3, '{"recipient":"[RECIPIENT FULL NAME]","city":"Prizren","country":"Kosovo","agencies":["Western Union","MoneyGram","Ria"]}'::jsonb),
  ('wise', 4, '{"email":"[WISE EMAIL]","accountHolder":"[ACCOUNT HOLDER]"}'::jsonb)
on conflict (id) do nothing;

insert into public.testimonials (quote_sq, quote_en, author, location, published, sort)
select v.* from (values
  ('[REVIEW TEXT]', '[REVIEW TEXT]', '[CLIENT NAME 1]', '[CITY]', true, 1),
  ('[REVIEW TEXT]', '[REVIEW TEXT]', '[CLIENT NAME 2]', '[CITY]', true, 2),
  ('[REVIEW TEXT]', '[REVIEW TEXT]', '[CLIENT NAME 3]', '[CITY]', true, 3)
) as v(quote_sq, quote_en, author, location, published, sort)
where not exists (select 1 from public.testimonials);

insert into public.site_content (key, value) values
  ('hero', '{"videoPath":null,"posterPath":null,"headline":{"sq":["E qepur për","momentin tënd."],"en":["Made for","Your Moment."]},"subtitle":{"sq":"Fustane nusërie dhe mbrëmjeje, të punuara me dorë në Prizren dhe të qepura sipas masave të tua.","en":"Handmade bridal and evening dresses, crafted in Prizren and made to your measurements."}}'::jsonb),
  ('marquee', '{"sq":["Punuar me dorë në Prizren","Sipas masave të tua","Dërgesa në mbarë botën"],"en":["Handmade in Prizren","Made to measure","Worldwide shipping"]}'::jsonb),
  ('featured_collection', '{"slug":"ceremonia"}'::jsonb),
  ('contact', '{"whatsapp":"[PHONE NUMBER]","phone":"[PHONE NUMBER]","email":"[EMAIL]","address":"[STREET ADDRESS], Prizren","instagram":"jelafashionpz"}'::jsonb)
on conflict (key) do nothing;

commit;
