// Generates supabase/seed.sql from src/lib/catalog/seed-data.ts.
// Run: npm run db:seed-sql
import { writeFileSync } from "node:fs";
import {
  categories,
  collections,
  discountCodes,
  measurementDefinitions,
  paymentMethods,
  products,
  shippingZones,
  siteContent,
  testimonials,
} from "../src/lib/catalog/seed-data";

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (v: string[]) => (v.length ? `array[${v.map(q).join(", ")}]` : "'{}'::text[]");
const cents = (eur: number) => Math.round(eur * 100);
const lines: string[] = [];
const out = (s: string) => lines.push(s);

out("-- GENERATED by scripts/generate-seed.ts from src/lib/catalog/seed-data.ts. Do not edit.");
out("-- SAMPLE data: replace products, prices, shipping rates and placeholders in the admin panel.");
out("begin;");
out("");

out("insert into public.categories (id, name_sq, name_en, intro_sq, intro_en, sort) values");
out(
  categories
    .map((c) => `  (${q(c.id)}, ${q(c.name.sq)}, ${q(c.name.en)}, ${q(c.intro.sq)}, ${q(c.intro.en)}, ${c.sort})`)
    .join(",\n") + "\non conflict (id) do nothing;\n",
);

out("insert into public.measurement_definitions (id, kind, view, label_sq, label_en, hint_sq, hint_en, min_cm, max_cm, always_required, sort) values");
out(
  measurementDefinitions
    .map(
      (m, i) =>
        `  (${q(m.id)}, ${q(m.kind)}, ${q(m.view)}, ${q(m.label.sq)}, ${q(m.label.en)}, ${q(m.hint.sq)}, ${q(m.hint.en)}, ${m.minCm}, ${m.maxCm}, ${m.alwaysRequired}, ${i + 1})`,
    )
    .join(",\n") + "\non conflict (id) do nothing;\n",
);

for (const p of products) {
  out(`-- ${p.name.en}`);
  out(
    `insert into public.products (slug, category_id, name_sq, name_en, description_sq, description_en, fabric_care_sq, fabric_care_en, price_cents, availability, production_weeks, length, sleeves, silhouette, published, featured, published_at)
values (${q(p.slug)}, ${q(p.category)}, ${q(p.name.sq)}, ${q(p.name.en)}, ${q(p.description.sq)}, ${q(p.description.en)}, ${q(p.fabricCare.sq)}, ${q(p.fabricCare.en)}, ${cents(p.priceEUR)}, ${q(p.availability)}, ${p.productionWeeks ?? "null"}, ${q(p.length)}, ${q(p.sleeves)}, ${q(p.silhouette)}, true, ${!!p.featured}, now() - interval '${p.publishedDaysAgo} days')
on conflict (slug) do nothing;`,
  );
  const pid = `(select id from public.products where slug = ${q(p.slug)})`;
  out(
    `insert into public.product_colors (product_id, name_sq, name_en, hex, family, sort)\nselect ${pid}, v.* from (values\n${p.colors
      .map((c, i) => `  (${q(c.name.sq)}, ${q(c.name.en)}, ${q(c.hex)}, ${q(c.family)}, ${i})`)
      .join(",\n")}\n) as v(name_sq, name_en, hex, family, sort)\nwhere not exists (select 1 from public.product_colors where product_id = ${pid});`,
  );
  const sizes = Object.entries(p.sizes);
  if (sizes.length)
    out(
      `insert into public.product_sizes (product_id, size, stock) values\n${sizes
        .map(([s, n]) => `  (${pid}, ${q(s)}, ${n})`)
        .join(",\n")}\non conflict do nothing;`,
    );
  if (p.measurements.length)
    out(
      `insert into public.product_measurements (product_id, measurement_id) values\n${p.measurements
        .map((m) => `  (${pid}, ${q(m)})`)
        .join(",\n")}\non conflict do nothing;`,
    );
  out("");
}

for (const c of collections) {
  out(
    `insert into public.collections (slug, name_sq, name_en, description_sq, description_en, published, sort)
values (${q(c.slug)}, ${q(c.name.sq)}, ${q(c.name.en)}, ${q(c.description.sq)}, ${q(c.description.en)}, true, ${c.sort})
on conflict (slug) do nothing;`,
  );
  out(
    `insert into public.collection_products (collection_id, product_id, sort)\nselect c.id, p.id, v.sort from (values ${c.products
      .map((s, i) => `(${q(s)}, ${i})`)
      .join(", ")}) as v(slug, sort)\njoin public.products p on p.slug = v.slug\njoin public.collections c on c.slug = ${q(c.slug)}\non conflict do nothing;\n`,
  );
}

out("-- Shipping (sample rates)");
out("do $$\ndeclare z uuid;\nbegin\n  if exists (select 1 from public.shipping_zones) then return; end if;");
shippingZones.forEach((z, zi) => {
  out(
    `  insert into public.shipping_zones (name_sq, name_en, countries, is_fallback, sort) values (${q(z.name.sq)}, ${q(z.name.en)}, ${arr(z.countries)}, ${z.isFallback}, ${zi}) returning id into z;`,
  );
  z.rates.forEach((r, ri) =>
    out(
      `  insert into public.shipping_rates (zone_id, name_sq, name_en, price_cents, free_over_cents, min_days, max_days, sort) values (z, ${q(r.name.sq)}, ${q(r.name.en)}, ${cents(r.priceEUR)}, ${r.freeOverEUR == null ? "null" : cents(r.freeOverEUR)}, ${r.minDays}, ${r.maxDays}, ${ri});`,
    ),
  );
});
out("end $$;\n");

out("insert into public.discount_codes (code, kind, value, usage_limit, expires_at) values");
out(
  discountCodes.map((d) => `  (${q(d.code)}, ${q(d.kind)}, ${d.value}, ${d.usageLimit}, ${q(d.expiresAt)})`).join(",\n") +
    "\non conflict (code) do nothing;\n",
);

out("insert into public.payment_methods (id, sort, details) values");
out(paymentMethods.map((m) => `  (${q(m.id)}, ${m.sort}, ${j(m.details)})`).join(",\n") + "\non conflict (id) do nothing;\n");

out("insert into public.testimonials (quote_sq, quote_en, author, location, published, sort)");
out(
  `select v.* from (values\n${testimonials
    .map((t) => `  (${q(t.quote.sq)}, ${q(t.quote.en)}, ${q(t.author)}, ${q(t.location)}, true, ${t.sort})`)
    .join(",\n")}\n) as v(quote_sq, quote_en, author, location, published, sort)\nwhere not exists (select 1 from public.testimonials);\n`,
);

out("insert into public.site_content (key, value) values");
out(
  Object.entries(siteContent)
    .map(([k, v]) => `  (${q(k)}, ${j(v)})`)
    .join(",\n") + "\non conflict (key) do nothing;\n",
);

out("commit;");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log("Wrote supabase/seed.sql");
