/**
 * Sample catalog and content. Single source of truth for:
 *  - supabase/seed.sql (generated by `npm run db:seed-sql`)
 *  - the local fallback used when Supabase env vars are not set
 *
 * Everything here is SAMPLE data to be replaced in the admin panel. Prices, shipping rates
 * and product copy are illustrative; nothing states a fact about the atelier beyond the
 * confirmed ones (name, Prizren, Instagram, handmade, custom sizes, worldwide shipping).
 */

export type Bilingual = { sq: string; en: string };

export type SeedMeasurement = {
  id: string;
  kind: "around" | "straight" | "heel";
  view: "front" | "back" | "side" | "shoe";
  label: Bilingual;
  hint: Bilingual;
  minCm: number;
  maxCm: number;
  alwaysRequired: boolean;
};

export type SeedColor = { name: Bilingual; hex: string; family: string };

export type SeedProduct = {
  slug: string;
  category: "bridal" | "evening" | "short";
  name: Bilingual;
  description: Bilingual;
  fabricCare: Bilingual;
  priceEUR: number;
  availability: "in_stock" | "made_to_order";
  productionWeeks: number | null;
  length: "mini" | "knee" | "midi" | "floor";
  sleeves: "sleeveless" | "short" | "long";
  silhouette: string;
  colors: SeedColor[];
  /** Stock per standard size; omitted sizes are not offered in standard sizing. */
  sizes: Partial<Record<"XS" | "S" | "M" | "L" | "XL" | "XXL", number>>;
  /** Conditional measurements on top of the always-required ones. */
  measurements: string[];
  featured?: boolean;
  /** Days before seeding; drives "New in" order. */
  publishedDaysAgo: number;
};

export const categories = [
  {
    id: "bridal",
    name: { sq: "Nusëri", en: "Bridal" },
    intro: {
      sq: "Fustane nusërie të punuara me dorë në Prizren, në masat standarde ose të qepura sipas masave të tua.",
      en: "Handmade wedding dresses from Prizren, in standard sizes or cut to your measurements.",
    },
    sort: 1,
  },
  {
    id: "evening",
    name: { sq: "Mbrëmje", en: "Evening" },
    intro: {
      sq: "Fustane mbrëmjeje për ceremoni, darka dhe netë që mbahen mend.",
      en: "Evening dresses for ceremonies, dinners and nights worth remembering.",
    },
    sort: 2,
  },
  {
    id: "short",
    name: { sq: "Të shkurtra", en: "Short" },
    intro: {
      sq: "Fustane të shkurtra për kurorëzimin civil, festat dhe mbrëmjet më të lira.",
      en: "Short dresses for civil ceremonies, celebrations and lighter evenings.",
    },
    sort: 3,
  },
] as const;

export const measurementDefinitions: SeedMeasurement[] = [
  {
    id: "height",
    kind: "straight",
    view: "front",
    label: { sq: "Gjatësia e trupit", en: "Height" },
    hint: {
      sq: "Zbathur, drejt pranë murit, nga dyshemeja deri në majë të kokës.",
      en: "Barefoot, standing straight against a wall, from the floor to the top of your head.",
    },
    minCm: 140,
    maxCm: 200,
    alwaysRequired: true,
  },
  {
    id: "bust",
    kind: "around",
    view: "front",
    label: { sq: "Perimetri i gjoksit", en: "Bust circumference" },
    hint: {
      sq: "Rreth pjesës më të plotë të gjoksit, me shiritin drejt përmes shpinës.",
      en: "Around the fullest part of your bust, with the tape level across your back.",
    },
    minCm: 70,
    maxCm: 150,
    alwaysRequired: true,
  },
  {
    id: "underbust",
    kind: "around",
    view: "front",
    label: { sq: "Perimetri nën gjoks", en: "Under bust circumference" },
    hint: {
      sq: "Menjëherë nën gjoks, aty ku qëndron shiriti i sutjenës.",
      en: "Directly under your bust, where a bra band sits.",
    },
    minCm: 60,
    maxCm: 130,
    alwaysRequired: true,
  },
  {
    id: "waist",
    kind: "around",
    view: "front",
    label: { sq: "Perimetri i belit", en: "Waist circumference" },
    hint: {
      sq: "Rreth pjesës më të ngushtë të belit, zakonisht pak mbi kërthizë.",
      en: "Around the narrowest part of your waist, usually just above the navel.",
    },
    minCm: 50,
    maxCm: 140,
    alwaysRequired: true,
  },
  {
    id: "hips",
    kind: "around",
    view: "side",
    label: { sq: "Perimetri i vitheve në pjesën më të gjerë", en: "Hip circumference at the fullest part" },
    hint: {
      sq: "Me këmbët bashkë, rreth pjesës më të plotë të vitheve.",
      en: "Feet together, around the fullest part of your seat.",
    },
    minCm: 75,
    maxCm: 160,
    alwaysRequired: true,
  },
  {
    id: "shoulder_width",
    kind: "straight",
    view: "back",
    label: { sq: "Gjerësia e shpatullave", en: "Shoulder width" },
    hint: {
      sq: "Përmes shpinës, nga maja e njërës shpatull te maja e tjetrës.",
      en: "Across your back, from one shoulder point to the other.",
    },
    minCm: 30,
    maxCm: 55,
    alwaysRequired: true,
  },
  {
    id: "hollow_to_floor",
    kind: "straight",
    view: "front",
    label: { sq: "Nga gropëza e qafës deri në dysheme", en: "Hollow to floor" },
    hint: {
      sq: "Zbathur, nga gropëza në fund të qafës drejt poshtë deri në dysheme.",
      en: "Barefoot, from the hollow at the base of your neck straight down to the floor.",
    },
    minCm: 120,
    maxCm: 175,
    alwaysRequired: true,
  },
  {
    id: "heel_height",
    kind: "heel",
    view: "shoe",
    label: { sq: "Lartësia e takës që do të mbash", en: "Heel height you will wear" },
    hint: {
      sq: "Nga dyshemeja deri aty ku mbështetet thembra. Shkruaj 0 për këpucë pa takë.",
      en: "From the floor to where your heel rests. Enter 0 for flat shoes.",
    },
    minCm: 0,
    maxCm: 15,
    alwaysRequired: true,
  },
  {
    id: "neck",
    kind: "around",
    view: "front",
    label: { sq: "Perimetri i qafës", en: "Neck circumference" },
    hint: {
      sq: "Rreth bazës së qafës, me një gisht nën shirit.",
      en: "Around the base of your neck, with one finger under the tape.",
    },
    minCm: 28,
    maxCm: 50,
    alwaysRequired: false,
  },
  {
    id: "bicep",
    kind: "around",
    view: "front",
    label: { sq: "Perimetri i krahut", en: "Bicep circumference" },
    hint: {
      sq: "Rreth pjesës më të plotë të krahut të sipërm, me krahun të lirshëm.",
      en: "Around the fullest part of your upper arm, arm relaxed.",
    },
    minCm: 20,
    maxCm: 50,
    alwaysRequired: false,
  },
  {
    id: "sleeve_length",
    kind: "straight",
    view: "side",
    label: { sq: "Gjatësia e mëngës", en: "Sleeve length" },
    hint: {
      sq: "Nga maja e shpatullës deri te kocka e kyçit, me krahun pak të përkulur.",
      en: "From the shoulder point to the wrist bone, arm slightly bent.",
    },
    minCm: 40,
    maxCm: 70,
    alwaysRequired: false,
  },
  {
    id: "wrist",
    kind: "around",
    view: "front",
    label: { sq: "Perimetri i kyçit të dorës", en: "Wrist circumference" },
    hint: {
      sq: "Rreth kyçit të dorës, pak mbi kockën e kyçit.",
      en: "Around your wrist, just above the wrist bone.",
    },
    minCm: 12,
    maxCm: 25,
    alwaysRequired: false,
  },
  {
    id: "front_waist_length",
    kind: "straight",
    view: "front",
    label: { sq: "Gjatësia e përparme deri në bel", en: "Front waist length" },
    hint: {
      sq: "Nga shpatulla, aty ku takon qafën, mbi majën e gjoksit deri në bel.",
      en: "From where your shoulder meets your neck, over the bust point, down to the waist.",
    },
    minCm: 30,
    maxCm: 55,
    alwaysRequired: false,
  },
  {
    id: "back_length",
    kind: "straight",
    view: "back",
    label: { sq: "Gjatësia e shpinës", en: "Back length" },
    hint: {
      sq: "Nga kocka në fund të qafës drejt poshtë deri në bel.",
      en: "From the bone at the base of your neck straight down to your waist.",
    },
    minCm: 32,
    maxCm: 50,
    alwaysRequired: false,
  },
  {
    id: "bust_point_height",
    kind: "straight",
    view: "front",
    label: { sq: "Lartësia e majës së gjoksit", en: "Bust point height" },
    hint: {
      sq: "Nga shpatulla, aty ku takon qafën, deri te maja e gjoksit.",
      en: "From where your shoulder meets your neck down to the bust point.",
    },
    minCm: 18,
    maxCm: 35,
    alwaysRequired: false,
  },
  {
    id: "hollow_to_hem",
    kind: "straight",
    view: "front",
    label: { sq: "Nga gropëza e qafës deri te fundi", en: "Hollow to hem" },
    hint: {
      sq: "Nga gropëza në fund të qafës deri aty ku dëshiron të përfundojë fustani.",
      en: "From the hollow at the base of your neck to where you want the hem to fall.",
    },
    minCm: 60,
    maxCm: 120,
    alwaysRequired: false,
  },
  {
    id: "waist_to_knee",
    kind: "straight",
    view: "side",
    label: { sq: "Nga beli deri te gjuri", en: "Waist to knee" },
    hint: {
      sq: "Nga beli natyral deri në mes të gjurit.",
      en: "From your natural waist to the middle of your knee.",
    },
    minCm: 45,
    maxCm: 70,
    alwaysRequired: false,
  },
];

const SLEEVES = ["bicep", "sleeve_length", "wrist"];
const BODICE = ["front_waist_length", "back_length", "bust_point_height"];

const care = {
  delicate: {
    sq: "Pastrim kimik. Ruaje të varur në mbulesën e pambuktë që vjen me fustanin, larg dritës së drejtpërdrejtë.",
    en: "Dry clean only. Store hanging in the cotton cover it arrives in, away from direct light.",
  },
  sturdy: {
    sq: "Pastrim kimik. Hekuros me avull nga ana e brendshme, në temperaturë të ulët.",
    en: "Dry clean only. Steam from the inside at a low temperature.",
  },
} satisfies Record<string, Bilingual>;

export const products: SeedProduct[] = [
  // Bridal
  {
    slug: "drita",
    category: "bridal",
    name: { sq: "Drita", en: "Drita" },
    description: {
      sq: "Fustan nusërie në krep mëndafshi, me jakë të lartë dhe mëngë të gjata. Një vijë e pastër që lë dritën të bjerë mbi ty.",
      en: "A silk crepe wedding gown with a high neck and long sleeves. One clean line that lets the light fall on you.",
    },
    fabricCare: care.delicate,
    priceEUR: 1450,
    availability: "made_to_order",
    productionWeeks: 8,
    length: "floor",
    sleeves: "long",
    silhouette: "column",
    colors: [
      { name: { sq: "Fildish", en: "Ivory" }, hex: "#F4EDE1", family: "ivory" },
      { name: { sq: "E bardhë", en: "White" }, hex: "#FBFAF7", family: "white" },
    ],
    sizes: { XS: 0, S: 1, M: 1, L: 0, XL: 0, XXL: 0 },
    measurements: ["neck", ...SLEEVES],
    featured: true,
    publishedDaysAgo: 3,
  },
  {
    slug: "bora",
    category: "bridal",
    name: { sq: "Bora", en: "Bora" },
    description: {
      sq: "Fustan me fund të gjerë prej tyli dhe korse të modeluar me dorë. Shtresa të lehta që lëvizin me çdo hap.",
      en: "A full tulle skirt beneath a hand-shaped corset. Light layers that move with every step.",
    },
    fabricCare: care.delicate,
    priceEUR: 1600,
    availability: "made_to_order",
    productionWeeks: 10,
    length: "floor",
    sleeves: "sleeveless",
    silhouette: "ball-gown",
    colors: [
      { name: { sq: "Fildish", en: "Ivory" }, hex: "#F4EDE1", family: "ivory" },
      { name: { sq: "Shampanjë", en: "Champagne" }, hex: "#EADBC4", family: "champagne" },
    ],
    sizes: { XS: 0, S: 0, M: 0, L: 0, XL: 0, XXL: 0 },
    measurements: BODICE,
    featured: true,
    publishedDaysAgo: 12,
  },
  {
    slug: "lirika",
    category: "bridal",
    name: { sq: "Lirika", en: "Lirika" },
    description: {
      sq: "Dantellë mbi krep, me shpatulla të zbuluara dhe fund në formë A. Butë, romantike dhe e lehtë për t'u mbajtur gjithë natën.",
      en: "Lace over crepe, off the shoulder, with an A-line skirt. Soft, romantic and easy to wear all night.",
    },
    fabricCare: care.delicate,
    priceEUR: 1250,
    availability: "in_stock",
    productionWeeks: null,
    length: "floor",
    sleeves: "short",
    silhouette: "a-line",
    colors: [{ name: { sq: "Fildish", en: "Ivory" }, hex: "#F4EDE1", family: "ivory" }],
    sizes: { XS: 1, S: 2, M: 2, L: 1, XL: 0, XXL: 0 },
    measurements: [],
    publishedDaysAgo: 30,
  },
  {
    slug: "yllka",
    category: "bridal",
    name: { sq: "Yllka", en: "Yllka" },
    description: {
      sq: "Siluetë sirenë në saten, me qëndisje të imët që ngjitet nga fundi. Për nusen që do të ndihet e mbledhur dhe e sigurt.",
      en: "A satin mermaid silhouette with fine embroidery rising from the hem. For the bride who wants to feel held and certain.",
    },
    fabricCare: care.delicate,
    priceEUR: 1380,
    availability: "made_to_order",
    productionWeeks: 9,
    length: "floor",
    sleeves: "sleeveless",
    silhouette: "mermaid",
    colors: [
      { name: { sq: "Fildish", en: "Ivory" }, hex: "#F4EDE1", family: "ivory" },
      { name: { sq: "Rozë e zbehtë", en: "Blush" }, hex: "#EBD3CB", family: "blush" },
    ],
    sizes: { XS: 0, S: 0, M: 0, L: 0, XL: 0, XXL: 0 },
    measurements: BODICE,
    publishedDaysAgo: 45,
  },
  // Evening
  {
    slug: "nata",
    category: "evening",
    name: { sq: "Nata", en: "Nata" },
    description: {
      sq: "Kadife e zezë, mëngë të gjata dhe një prerje e thellë në shpinë. E qetë përpara, e guximshme kur largohesh.",
      en: "Black velvet, long sleeves and a deep cut at the back. Quiet from the front, daring as you walk away.",
    },
    fabricCare: care.sturdy,
    priceEUR: 690,
    availability: "in_stock",
    productionWeeks: null,
    length: "floor",
    sleeves: "long",
    silhouette: "column",
    colors: [
      { name: { sq: "E zezë", en: "Black" }, hex: "#1E1B1A", family: "black" },
      { name: { sq: "Bordo", en: "Burgundy" }, hex: "#5C1F2B", family: "red" },
    ],
    sizes: { XS: 1, S: 2, M: 3, L: 2, XL: 1, XXL: 1 },
    measurements: SLEEVES,
    featured: true,
    publishedDaysAgo: 1,
  },
  {
    slug: "vera",
    category: "evening",
    name: { sq: "Vera", en: "Vera" },
    description: {
      sq: "Fustan i rrëshqitshëm në saten shampanjë, me rripa të hollë. Bie lirshëm dhe kap dritën në çdo lëvizje.",
      en: "A champagne satin slip dress on fine straps. It falls loosely and catches the light as you move.",
    },
    fabricCare: care.delicate,
    priceEUR: 520,
    availability: "in_stock",
    productionWeeks: null,
    length: "floor",
    sleeves: "sleeveless",
    silhouette: "slip",
    colors: [
      { name: { sq: "Shampanjë", en: "Champagne" }, hex: "#D9C3A0", family: "champagne" },
      { name: { sq: "Argjend", en: "Silver" }, hex: "#C9C7C4", family: "silver" },
    ],
    sizes: { XS: 2, S: 3, M: 3, L: 2, XL: 1, XXL: 0 },
    measurements: [],
    publishedDaysAgo: 6,
  },
  {
    slug: "hena",
    category: "evening",
    name: { sq: "Hëna", en: "Hëna" },
    description: {
      sq: "Fustan me xixa të qepura një nga një, me jakë të lartë dhe shpinë të hapur. Për netët kur do të shkëlqesh pa u përpjekur.",
      en: "Sequins sewn on one by one, a high neck and an open back. For nights when you want to shine without trying.",
    },
    fabricCare: care.delicate,
    priceEUR: 890,
    availability: "made_to_order",
    productionWeeks: 6,
    length: "floor",
    sleeves: "sleeveless",
    silhouette: "column",
    colors: [
      { name: { sq: "Argjend", en: "Silver" }, hex: "#BDBAB5", family: "silver" },
      { name: { sq: "Ar i zbehtë", en: "Pale gold" }, hex: "#D8C08E", family: "champagne" },
    ],
    sizes: { XS: 0, S: 0, M: 1, L: 0, XL: 0, XXL: 0 },
    measurements: ["neck"],
    publishedDaysAgo: 9,
  },
  {
    slug: "mira",
    category: "evening",
    name: { sq: "Mira", en: "Mira" },
    description: {
      sq: "Krep smeraldi me një shpatull të zbuluar dhe korse të brendshëm. Një ngjyrë e thellë për një mbrëmje të gjatë.",
      en: "Emerald crepe on one shoulder, with an inner corset. A deep colour for a long evening.",
    },
    fabricCare: care.sturdy,
    priceEUR: 760,
    availability: "made_to_order",
    productionWeeks: 5,
    length: "floor",
    sleeves: "sleeveless",
    silhouette: "sheath",
    colors: [
      { name: { sq: "Smerald", en: "Emerald" }, hex: "#1F4A3D", family: "green" },
      { name: { sq: "E zezë", en: "Black" }, hex: "#1E1B1A", family: "black" },
    ],
    sizes: { XS: 0, S: 1, M: 1, L: 1, XL: 0, XXL: 0 },
    measurements: BODICE,
    publishedDaysAgo: 18,
  },
  {
    slug: "zana",
    category: "evening",
    name: { sq: "Zana", en: "Zana" },
    description: {
      sq: "Shifon në rozë të pluhurosur, me mëngë të gjata të tejdukshme që rrjedhin si pelerinë. E lehtë si ajri.",
      en: "Dusty rose chiffon with long sheer sleeves that flow like a cape. As light as air.",
    },
    fabricCare: care.delicate,
    priceEUR: 640,
    availability: "in_stock",
    productionWeeks: null,
    length: "floor",
    sleeves: "long",
    silhouette: "a-line",
    colors: [
      { name: { sq: "Rozë e pluhurosur", en: "Dusty rose" }, hex: "#C9A3A0", family: "blush" },
      { name: { sq: "Blu e mjegullt", en: "Mist blue" }, hex: "#A9B4BF", family: "blue" },
    ],
    sizes: { XS: 1, S: 1, M: 2, L: 2, XL: 1, XXL: 1 },
    measurements: SLEEVES,
    publishedDaysAgo: 24,
  },
  // Short
  {
    slug: "lule",
    category: "short",
    name: { sq: "Lule", en: "Lule" },
    description: {
      sq: "Dantellë në ngjyrë rozë të zbehtë, deri te gjuri, me mëngë të shkurtra. E përshtatshme për kurorëzimin civil.",
      en: "Blush lace to the knee with short sleeves. Made for a civil ceremony.",
    },
    fabricCare: care.delicate,
    priceEUR: 420,
    availability: "in_stock",
    productionWeeks: null,
    length: "knee",
    sleeves: "short",
    silhouette: "a-line",
    colors: [
      { name: { sq: "Rozë e zbehtë", en: "Blush" }, hex: "#EBD3CB", family: "blush" },
      { name: { sq: "Fildish", en: "Ivory" }, hex: "#F4EDE1", family: "ivory" },
    ],
    sizes: { XS: 2, S: 3, M: 3, L: 2, XL: 1, XXL: 1 },
    measurements: ["hollow_to_hem"],
    featured: true,
    publishedDaysAgo: 2,
  },
  {
    slug: "era",
    category: "short",
    name: { sq: "Era", en: "Era" },
    description: {
      sq: "Fustan i shkurtër prej krepi në ngjyrë fildishi, me një fjongo të madhe në shpinë. I thjeshtë, me një detaj që mbahet mend.",
      en: "A short ivory crepe dress with a large bow at the back. Simple, with one detail that stays with you.",
    },
    fabricCare: care.sturdy,
    priceEUR: 350,
    availability: "in_stock",
    productionWeeks: null,
    length: "mini",
    sleeves: "sleeveless",
    silhouette: "shift",
    colors: [
      { name: { sq: "Fildish", en: "Ivory" }, hex: "#F4EDE1", family: "ivory" },
      { name: { sq: "E zezë", en: "Black" }, hex: "#1E1B1A", family: "black" },
    ],
    sizes: { XS: 2, S: 2, M: 3, L: 2, XL: 1, XXL: 0 },
    measurements: ["waist_to_knee"],
    publishedDaysAgo: 14,
  },
  {
    slug: "dea",
    category: "short",
    name: { sq: "Dea", en: "Dea" },
    description: {
      sq: "Saten i zi deri te gjuri, me korse të brendshëm dhe prerje të pastër. Për darkën pas ceremonisë.",
      en: "Black satin to the knee, with an inner corset and a clean cut. For the dinner after the ceremony.",
    },
    fabricCare: care.sturdy,
    priceEUR: 480,
    availability: "made_to_order",
    productionWeeks: 4,
    length: "knee",
    sleeves: "sleeveless",
    silhouette: "sheath",
    colors: [
      { name: { sq: "E zezë", en: "Black" }, hex: "#1E1B1A", family: "black" },
      { name: { sq: "Bordo", en: "Burgundy" }, hex: "#5C1F2B", family: "red" },
    ],
    sizes: { XS: 0, S: 1, M: 1, L: 0, XL: 0, XXL: 0 },
    measurements: [...BODICE, "hollow_to_hem"],
    publishedDaysAgo: 21,
  },
];

export const collections = [
  {
    slug: "ceremonia",
    name: { sq: "Ceremonia", en: "Ceremony" },
    description: {
      sq: "Fustanet për ditën kur thua po.",
      en: "Dresses for the day you say yes.",
    },
    products: ["drita", "bora", "lirika", "yllka", "lule"],
    sort: 1,
  },
  {
    slug: "dritat-e-mbremjes",
    name: { sq: "Dritat e mbrëmjes", en: "Evening Light" },
    description: {
      sq: "Fustane që kapin dritën kur bie nata.",
      en: "Dresses that catch the light as night falls.",
    },
    products: ["nata", "vera", "hena", "mira", "zana", "dea"],
    sort: 2,
  },
];

/** SAMPLE rates, to be set in the admin panel before launch. */
export const shippingZones = [
  {
    name: { sq: "Kosovë", en: "Kosovo" },
    countries: ["XK"],
    isFallback: false,
    rates: [{ name: { sq: "Standarde", en: "Standard" }, priceEUR: 5, freeOverEUR: null, minDays: 1, maxDays: 3 }],
  },
  {
    name: { sq: "Shqipëri dhe Maqedoni e Veriut", en: "Albania and North Macedonia" },
    countries: ["AL", "MK"],
    isFallback: false,
    rates: [{ name: { sq: "Standarde", en: "Standard" }, priceEUR: 15, freeOverEUR: null, minDays: 3, maxDays: 6 }],
  },
  {
    name: { sq: "Evropë", en: "Europe" },
    countries: [
      "AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR", "GB", "GR", "HR", "HU", "IE",
      "IT", "LT", "LU", "LV", "ME", "MT", "NL", "NO", "PL", "PT", "RO", "RS", "SE", "SI", "SK",
    ],
    isFallback: false,
    rates: [
      { name: { sq: "Standarde", en: "Standard" }, priceEUR: 35, freeOverEUR: null, minDays: 5, maxDays: 10 },
      { name: { sq: "Ekspres", en: "Express" }, priceEUR: 60, freeOverEUR: null, minDays: 2, maxDays: 4 },
    ],
  },
  {
    name: { sq: "Pjesa tjetër e botës", en: "Rest of the world" },
    countries: [],
    isFallback: true,
    rates: [{ name: { sq: "Ndërkombëtare", en: "International" }, priceEUR: 70, freeOverEUR: null, minDays: 7, maxDays: 15 }],
  },
];

export const discountCodes = [
  { code: "MIRESEVINI10", kind: "percent" as const, value: 10, usageLimit: 100, expiresAt: "2027-12-31T23:59:59Z" },
];

export const paymentMethods = [
  { id: "paysera", sort: 1, details: {} },
  {
    id: "bank_transfer",
    sort: 2,
    details: { bankName: "[BANK NAME]", beneficiary: "[BENEFICIARY]", iban: "[IBAN]", swift: "[SWIFT]" },
  },
  {
    id: "cash_agency",
    sort: 3,
    details: { recipient: "[RECIPIENT FULL NAME]", city: "Prizren", country: "Kosovo", agencies: ["Western Union", "MoneyGram", "Ria"] },
  },
  { id: "wise", sort: 4, details: { email: "[WISE EMAIL]", accountHolder: "[ACCOUNT HOLDER]" } },
];

export const testimonials = [1, 2, 3].map((n) => ({
  quote: { sq: "[REVIEW TEXT]", en: "[REVIEW TEXT]" },
  author: `[CLIENT NAME ${n}]`,
  location: "[CITY]",
  sort: n,
}));

/** Homepage and contact content, editable in the admin panel (Phase 5). */
export const siteContent: Record<string, unknown> = {
  hero: {
    videoPath: null,
    posterPath: null,
    headline: { sq: ["E qepur për", "momentin tënd."], en: ["Made for", "Your Moment."] },
    subtitle: {
      sq: "Fustane nusërie dhe mbrëmjeje, të punuara me dorë në Prizren dhe të qepura sipas masave të tua.",
      en: "Handmade bridal and evening dresses, crafted in Prizren and made to your measurements.",
    },
  },
  marquee: {
    sq: ["Punuar me dorë në Prizren", "Sipas masave të tua", "Dërgesa në mbarë botën"],
    en: ["Handmade in Prizren", "Made to measure", "Worldwide shipping"],
  },
  featured_collection: { slug: "ceremonia" },
  contact: {
    whatsapp: "[PHONE NUMBER]",
    phone: "[PHONE NUMBER]",
    email: "[EMAIL]",
    address: "[STREET ADDRESS], Prizren",
    instagram: "jelafashionpz",
  },
};
